### PR TITLE
Release v0.46.0

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:

Release v0.46.0

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by ffjlabo** [comment]
@t-kikuc Sorry for re-reviewing 🙏  I Added docs for v0.46.0 [27f4098](https://github.com/pipe-cd/pipecd/pull/4775/commits/27f40986631ce2045a3a3d9005db65072c1ea169)

**Comment by khanhtc1202** [comment]
@ffjlabo Please re-gen docs due to this pr is merged recently
https://github.com/pipe-cd/pipecd/pull/4770

**Comment by ffjlabo** [comment]
@khanhtc1202 Rebase to master and re-gen 🙏 [55a1494](https://github.com/pipe-cd/pipecd/pull/4775/commits/55a1494eee5b3d0a23b62b6948455039495be6de)

**Review by khanhtc1202 — APPROVED** [review]
👍

**Review by t-kikuc — APPROVED** [review]
🚀 🚀

**Comment by ffjlabo** [comment]
Thank you! Let's go 🚀 🚀 🚀

**Comment by ffjlabo** [comment]
It looks strange 👀 the diff is expected from v0.45.3 to the latest commit, but it includes older over v0.45.4.

**Pull request merged**
