### PR TITLE
Define new interface to handle RBAC role

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
plz ignore bot pointing out cuz I'll implement this later.

**Comment by knanao** [comment]
let me redesign RBAC on PipeCD.
/hold

**Comment by khanhtc1202** [comment]
@knanao From the last time of discussion about builtin RBAC, I think we can close this PR and make another one (with the implementation), wdyt?

**Comment by knanao** [comment]
@khanhtc1202 
That makes sense.
Let me create another PR.
/close

**Pull request closed without merging**
