### PR TITLE
Support Drift Detection for ECS

### LINKED ISSUE #5005: [ECS] Support Drift Detection for ECS

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

Supported DriftDetection for ECS with some restrictions.

When synced:

image

When out-of-sync:
image

Restrictions: 
- If `desiredCount` of headManifest is 0 or not set, which means Autoscale may be enabled), diff of `desiredCount` will be ignored. 
    - cf. https://github.com/pipe-cd/pipecd/pull/5030
- Some parameters are ignored. (e.g. Tags, LoadBalancers)
    - See `detector.go` > `ignoreParameters()`
- Even if unintended drift tasksets exist and the diff is detected, automatic deployment will NOT remove the tasksets. 
    - If needed, we should fix the deployment logic of ECS.
    - If diff of other fields exists, `desiredCount`'s diff will also be shown (as the above image).

I will add docs about them in another PR.

**Which issue(s) this PR fixes**:

Fixes #5005

**Does this PR introduce a user-facing change?**: Yes,  users can detect drift for ECS

- **How are users affected by this change**: N/A
- **Is this breaking change**: no
- **How to migrate (if breaking change)**: no

### CODE REVIEW

**Review by ffjlabo — APPROVED** [review]
🚀

**Review by khanhtc1202 — COMMENTED** [review]
LGTM 👍

**Review by khanhtc1202 — APPROVED** [review]
LGTM 👍

**Pull request merged**
