### PR TITLE
Set 'gc.autoDetach' to false to be executed 'git gc' in the foreground by some git commands

### LINKED ISSUE #4760: Enable to execute 'git gc' in the foreground
**What would you like to be added**:
We need to set the config to enable to execute 'git gc' in the foreground just after cloning the source repo.
in particular, execute `git config gc.autoDetach false`.

**Why is this needed**:
Plan Preview frequently failed because of being executed `git gc` automatically when executing some git commands.

More details is here↓
discussion: https://github.com/pipe-cd/pipecd/discussions/4758

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:
Set 'gc.autoDetach' to false to be executed 'git gc' in the foreground by some git commands
**Which issue(s) this PR fixes**:

Fixes #4760

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by ffjlabo** [comment]
✅ tested on local :)

log↓
```log
received a plan-preview command to handle	{"command": "c0c563fb-7a78-43d3-ad5e-8e45f0f7cbf8"}
start building planpreview result for command c0c563fb-7a78-43d3-ad5e-8e45f0f7cbf8	{"command": "c0c563fb-7a78-43d3-ad5e-8e45f0f7cbf8"}
cloning ffjlabo-dev for the first time	{"repo-id": "ffjlabo-dev", "remote": "XXX", "repo-cache-path": "/var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/gitcache651340412/ffjlabo-dev"}
cloning a repo from cached one in local	{"repo-id": "ffjlabo-dev", "remote": "XXX", "repo-cache-path": "/var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/gitcache651340412/ffjlabo-dev", "src": "/var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/gitcache651340412/ffjlabo-dev", "dst": "/var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/plan-preview-builder-1425043400/1752730028"}
setting gc.autoDetach	{"repo-id": "ffjlabo-dev", "remote": "XXX", "repo-cache-path": "/var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/gitcache651340412/ffjlabo-dev", "gc.autoDetach": true}
successfully reported a failure command	{"command": "c0c563fb-7a78-43d3-ad5e-8e45f0f7cbf8"}
```

repo setting↓
```
% cd /var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/plan-preview-builder-1425043400/1752730028                    (git)-[main|merge]
% /var/folders/th/pq_q9v6j6_n_0fgx6v1_zp09_2tx_x/T/plan-preview-builder-1425043400/1752730028
% git config --get gc.autoDetach                                                                                    (git)-[main|merge]
true
```

**Review by khanhtc1202 — APPROVED** [review]
Here you go 🪨

**Review by t-kikuc — APPROVED** [review]
GREAT🚀 🚀

**Comment by ffjlabo** [comment]
Ooops... I mistook the default value... not true but false... Sorry I will fix it 🙏

**Pull request merged**
