### PR TITLE
[Snyk] Upgrade redux-thunk from 2.4.1 to 2.4.2

### PR DESCRIPTION
**Pull request by khanhtc1202**
snyk-top-banner

<h3>Snyk has created this PR to upgrade redux-thunk from 2.4.1 to 2.4.2.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.

<hr/>

- The recommended version is **1 version** ahead of your current version.

- The recommended version was released on **2 years ago**.

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - This PR was automatically created by Snyk using the credentials of a real user.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs._

**For more information:** 

> - 🧐 [View latest project report](https://app.snyk.io/org/pipecd/project/f41c5767-b506-4f59-beb9-ef662258eb9a?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 📜 [Customise PR templates](https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/customize-pr-templates)
> - 🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/pipecd/project/f41c5767-b506-4f59-beb9-ef662258eb9a/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)
> - 🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/pipecd/project/f41c5767-b506-4f59-beb9-ef662258eb9a/settings/integration?pkg&#x3D;redux-thunk&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":[],"fieldsUsed":[]},"dependencies":[{"name":"redux-thunk","from":"2.4.1","to":"2.4.2"}],"env":"prod","hasFixes":false,"isBreakingChange":false,"isMajorUpgrade":false,"issuesToFix":[],"prId":"d77fae56-461c-4f6c-ab56-9d8f7ebe8168","prPublicId":"d77fae56-461c-4f6c-ab56-9d8f7ebe8168","packageManager":"yarn","priorityScoreList":[],"projectPublicId":"f41c5767-b506-4f59-beb9-ef662258eb9a","projectUrl":"https://app.snyk.io/org/pipecd/project/f41c5767-b506-4f59-beb9-ef662258eb9a?utm_source=github&utm_medium=referral&page=upgrade-pr","prType":"upgrade","templateFieldSources":{"branchName":"default","commitMessage":"default","description":"default","title":"default"},"templateVariants":[],"type":"auto","upgrade":[],"upgradeInfo":{"versionsDiff":1,"publishedDate":"2022-11-04T01:56:36.659Z"},"vulns":[]}'

### CODE REVIEW

**Review by t-kikuc — COMMENTED** [review]
The upgrade contains only a tiny internal change.
https://github.com/reduxjs/redux-thunk/compare/v2.4.1...v2.4.2

But we need to fix `lint/web` error.

**Comment by Warashi** [comment]
I am supposed to close this PR.

The reasons are below.
- lint/web trapped with [a type check issue](https://github.com/reduxjs/redux-thunk/issues/333)
  - The type `ThunkAction` has a workaround in [the issue comments](https://github.com/reduxjs/redux-thunk/issues/333#issuecomment-1275599808).
  - The type `AsyncThunkAction` has no workaround, so we cannot fix it.
- The difference between v2.4.1 and v2.4.2 is very small, and there is no strong reason to keep up its version.

WDYT? @khanhtc1202 @t-kikuc @ffjlabo

**Comment by khanhtc1202** [comment]
I'm okay with close this PR 👍

**Comment by t-kikuc** [comment]
I agree, this PR does not contain important fixes.

**Pull request closed without merging**
