### PR TITLE
Revert "Release v0.46.1"

### PR DESCRIPTION
**Pull request by t-kikuc**
Reverts pipe-cd/pipecd#4859

to modify the release version from v0.46.1 to v0.47.0

### CODE REVIEW

**Comment by khanhtc1202** [comment]
DCO is not passed

**Review by ffjlabo — APPROVED** [review]
🚀

**Comment by t-kikuc** [comment]
@khanhtc1202 Sorry, i fixed

**Comment by ffjlabo** [comment]
📝 It's ok to fail the `prerelease/gh-release` because this PR updates the version in the RELEASE file from v0.46.1 to v0.46.0 inversely.

**Review by khanhtc1202 — APPROVED** [review]
👍

**Comment by t-kikuc** [comment]
close since v0.47.0 is released instead.

**Pull request closed without merging**
