### PR TITLE
Add a workflow to automate GitHub release

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
The first build of `release/gh-release` is failing since the path of RELEASE file on master is not updated yet.
Therefore let's ignore it.

**Comment by khanhtc1202** [comment]
we also need to update several places which uses content of file `release/RELEASE` but it can be done by a separated PR 👍

**Review by khanhtc1202 — APPROVED** [review]
Go bold

**Review by knanao — APPROVED** [review]
Nice catch!

**Comment by nghialv** [comment]
> we also need to update several places which uses content of file `release/RELEASE` but it can be done by a separated PR 👍

You're right. Thank for reminding me.

**Pull request merged**
