### PR TITLE
Enable to filter application by its piped

### LINKED ISSUE #4212: Enable to filter applications by its piped
**What would you like to be added**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by funera1**
**What this PR does / why we need it**:
Support for piped filtering of applications list with Web UI and pipectl

**Which issue(s) this PR fixes**:

Fixes #4212

**Does this PR introduce a user-facing change?**:
View example
Each application name is the same as piped name.
image

image

image
```release-note
NONE
```

### CODE REVIEW

**Comment by funera1** [comment]
image
image
imageimage

**Comment by knanao** [comment]
Cool, how about removing "All" as well as Application Name because it's not the kind of application.

**Review by knanao — COMMENTED** [review]
If we filter applications with piped, how do the matched applications line up?
If it's lined up following the updated time, I suppose you need to create a custom index.

**Comment by funera1** [comment]
Do you mean Piped name, not Application name?
The list of Piped names is implemented in Select, not Autocomplete like Application name, so it seemed difficult to specify all Piped without All.

**Comment by funera1** [comment]
>If we filter applications with piped, how do the matched applications line up?
If it's lined up following the updated time, I suppose you need to create a custom index.

I will investigate it. Thank you for nice review.

**Comment by knanao** [comment]
> Do you mean Piped name, not Application name?
Sorry, I mean I thought it's better not to use the "All" property, as well as the labels filter.

**Comment by funera1** [comment]
@knanao 
Please review this PR when you have time:bow:

**Comment by funera1** [comment]
https://user-images.githubusercontent.com/60760935/224869782-d044ef9f-b61b-4c05-be68-54d940b1b54c.mov

**Review by knanao — APPROVED** [review]

**Pull request merged**
