### PR TITLE
Update docs reflect new category structure

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Refine the docs structure
```

### CODE REVIEW

**Comment by nghialv** [comment]
@khanhtc1202 Lets update this PR, and then we can merge it.

**Comment by khanhtc1202** [comment]
> Lets update this PR, and then we can merge it.

It's done, PTAL when you have time 🙏

**Review by nghialv — APPROVED** [review]
Great!

**Review by knanao — APPROVED** [review]
Here we go🚀

**Pull request merged**
