### PR TITLE
Add label and description for examples

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
Does this PR just add labels? 
If not, I think there are some files which we should replace comment into description

**Comment by nghialv** [comment]
> This PR just add labels. right? If not, I think there are some files which we should replace comment into description

Sorry, let me fix the PR title. I also want to add the description for some applications to check.

**Comment by khanhtc1202** [comment]
Nice improvement 🙌 
/lgtm

**Comment by nghialv** [comment]
@knanao I fixed the PR title. PTAL.

**Pull request merged**
