### PR TITLE
Support update application api

### PR DESCRIPTION
**Pull request by sivchari**
**What this PR does / why we need it**:
Support update application operation through grpc api.

**Which issue(s) this PR fixes**:

Fixes #4275 
#4275 for some reason no longer passes CI (I wonder the problem 🤔 ).  So, this PR is a copy of #4275 . 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sivchari** [comment]
sign workflow is exists 🤔

**Comment by khanhtc1202** [comment]
@sivchari the GitHub bot on Slack reported that all checks are passed 😵‍💫
Screen Shot 2023-05-15 at 16 08 29

**Comment by khanhtc1202** [comment]
I found that configuration; it's a different one that needs to be unchecked on the branch protection config 🤣 
Screen Shot 2023-05-15 at 16 13 27

Anw, Nice work, thank you! @sivchari 🙌

**Comment by sivchari** [comment]
Oh, thanks for survey and all reviews. It was helpful 🐈

**Pull request merged**
