### PR TITLE
Web update for using RBAC with resource label

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Part of #4918 

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Review by t-kikuc — APPROVED** [review]
LTGM, thanks!

**Comment by ffjlabo** [comment]
@khanhtc1202 
[ASK]
Which resources do you expect to be restricted by the label?
I have concerns about the pattern `resources=*{env: dev};actions=*`.
PipeCD has 7 resources (application, deployment, event, piped, project, apiKey, insight), and some of them don't have the label. (e.g. piped) . 👀 
https://pipecd.dev/docs-v0.47.x/user-guide/managing-controlplane/auth/#configuring-the-pipecds-roles

**Comment by khanhtc1202** [comment]
> @khanhtc1202 
> 
> [ASK]
> 
> Which resources do you expect to be restricted by the label?
> 
> I have concerns about the pattern `resources=*{env: dev};actions=*`.
> 
> PipeCD has 7 resources (application, deployment, event, piped, project, apiKey, insight), and some of them don't have the label. (e.g. piped) . 👀 
> 
> https://pipecd.dev/docs-v0.47.x/user-guide/managing-controlplane/auth/#configuring-the-pipecds-roles

To simplify users' config, your mentioned pattern will be treated as all resource which have label `env:dev` and if it's resource without labels, just ignore the labels. Your point is a good catch, I will think about it while implementing the server side 👍

**Comment by ffjlabo** [comment]
OK, sounds nice 👍

**Review by ffjlabo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
