### PR TITLE
Add actions menu to application detail page

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Demo:

https://user-images.githubusercontent.com/32532742/175929390-e30a1abe-654e-43b3-a845-33d11811002a.mp4

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Add the ability to disable/enable and delete application on the application detail page
```

### CODE REVIEW

**Review by knanao — APPROVED** [review]
awesome!🥇

**Review by knanao — COMMENTED** [review]
I have one question.
Is the button fixed when scrolling?

**Comment by khanhtc1202** [comment]
> I have one question. Is the button fixed when scrolling?

yes, it stays on the bottom right position 😉

**Review by nghialv — APPROVED** [review]
Great!

**Pull request merged**
