### PR TITLE
Mark remote-upgrade and remote-config as beta status

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

I think it is time to escalate those features to a new status level since those features are used widely without any big issues.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Remote-upgrade and remote-config features are now at Beta status
```

### CODE REVIEW

**Comment by knanao** [comment]
:raised_hands:
/lgtm

**Comment by nakabonne** [comment]
We're on the same page.
/approve

**Comment by khanhtc1202** [comment]
just wonder why do we only update docs-dev? what about the /docs and /docs-v0.24.x since we don't touch it on the next release or such, so making the latest version docs update is good to me.

**Comment by nghialv** [comment]
It will be rolled out in the next release. I also added a RELEASE NOTE for this since it should be a notable change.
That is why only docs-dev has been updated.

**Pull request merged**
