### PR TITLE
Cherry pick #3900 #3901 #3905 #3908 #3910 #3911 to release v0.37.x

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by khanhtc1202 — APPROVED** [review]
lets go 🙌

**Comment by nghialv** [comment]
We don't need #3904?

**Comment by nghialv** [comment]
If all recently added commits are ok, how about merging the master branch to `release-v0.37.x` branch to release?

**Comment by khanhtc1202** [comment]
> If all recently added commits are ok, how about merging the master branch to `release-v0.37.x` branch to release?

lgtm 👍 it reduces the risk of missing commit

**Comment by knanao** [comment]
@nghialv @khanhtc1202 
Okay, let's do that after editing RELEASE file and close this PR.

**Pull request closed without merging**
