### PR TITLE
Use chan only to notify command is done

### LINKED ISSUE #4630: A unit test is flaky: TestGracefulStopCommand
**What happened**:

test passes

**What you expected to happen**:

not passes

**How to reproduce it**:

```
--- FAIL: TestGracefulStopCommand (0.00s)
    --- FAIL: TestGracefulStopCommand/graceful_stop_after_very_short_time (0.00s)
        binary_test.go:48: 
            	Error Trace:	/home/runner/work/pipecd/pipecd/pkg/app/launcher/cmd/launcher/binary_test.go:48
            	Error:      	Should be false
            	Test:       	TestGracefulStopCommand/graceful_stop_after_very_short_time
```

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by Warashi**
**What this PR does / why we need it**:

The original IsRunning method has a bug when the command exits with an error.
After the command is done with an error, IsRunning returns true once if GracefulStop is not called.
This comes from using `chan error` to both pass the result and notify the finish.
This PR splits these things to `chan struct{}` and `atomic.Pointer[error]`.

**Which issue(s) this PR fixes**:

The flaky test `TestGracefulStopCommand`.

Fixes #4630

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by Warashi** [comment]
I'll run the test 5 times and make this PR ready for review if all tests are passed.

**Comment by Warashi** [comment]
I realized there are no test for the result of GracefulStop, so I added that.

**Comment by Warashi** [comment]
> I'll run the test 5 times and make this PR ready for review if all tests are passed.

The tests are passed 5 times.

https://github.com/pipe-cd/pipecd/actions/runs/11100844567/job/30838021571

スクリーンショット 2024-09-30 16 07 47

**Review by t-kikuc — APPROVED** [review]

**Review by khanhtc1202 — APPROVED** [review]
Got your point, LGTM 👍

**Pull request merged**
