### PR TITLE
Use codegen to generate Go mock files

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by knanao** [comment]
Nice catch!
Let's add validation job for CI later in order to check whether we generated mock or something.
/lgtm

**Comment by nghialv** [comment]
@knanao Thanks for your comment.
That validating job has already been added and it is working now.
https://github.com/pipe-cd/pipecd/blob/master/.github/workflows/validate-generated-code.yaml

It validated this PR as well.
https://github.com/pipe-cd/pipecd/runs/5442708971?check_suite_focus=true

**Comment by knanao** [comment]
@nghialv 
Oh, how fast! Thank you.

**Comment by nghialv** [comment]
Thank you. Please let me merge this.
/approve

**Pull request merged**
