### PR TITLE
Add some tests and fix bug that error occurs when approvers are nil

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ono-max** [comment]
Oh, let me check why this test failed.

**Comment by ono-max** [comment]
@nghialv 

Sorry, could you check this one again? Thanks.

**Comment by nghialv** [comment]
Nice.
/lgtm

**Comment by khanhtc1202** [comment]
Way to go
/approve

**Pull request merged**
