### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by anhpnv**
- Just fix small typos

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Thank @anhpnv , could you update the commit message with `Signed-of-by` using `git commit -s` 🙏 
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

**Comment by anhpnv** [comment]
> Thank @anhpnv , could you update the commit message with `Signed-of-by` using `git commit -s` 🙏 https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

Hi @khanhtc1202 , I have signed off on my commit. Can you please review it ? 😄

**Review by khanhtc1202 — APPROVED** [review]
Thank you 🤝

**Comment by hungran** [comment]
what a typo :D

**Pull request merged**
