### PR TITLE
Google Analytics 4 (GA4): configure CNCF site ID

### PR DESCRIPTION
**Pull request by chalin**
- Follow up to the following request: https://cncfservicedesk.atlassian.net/browse/CNCFSD-1859
- Contributes to #4341

/cc @nate-double-u

### CODE REVIEW

**Review by t-kikuc — APPROVED** [review]
thank you so much!!

**Review by khanhtc1202 — APPROVED** [review]
Thank you @chalin @nate-double-u 😄

**Comment by khanhtc1202** [comment]
@chalin Looks like the commit has not been signed yet. Could you sign the commit with `git commit -s` 🙏

**Comment by chalin** [comment]
Hi. Do you know why the DCO check seems to be blocked?

> image

I submitted this PR via the GH web i/f, and for other DCO-based projects it'll sign my PRs for me. I can't tell whether this one is signed or not because the check seems stalled. I'm not at my main work computer now so I can't "force sign" it. I'll do that later today if we can't get the DCO check to confirm whether or not I've actually signed. Thanks ✨

**Comment by khanhtc1202** [comment]
Hi @chalin, sorry for the wrong mentioning 🙏 It was an issue on the DCO bot GitHub App we used for PipeCD. Let us check and update from our end. Thanks for your quick response 😄 
https://github.com/dcoapp/app/issues/211

**Comment by khanhtc1202** [comment]
Hi @chalin, The DCO check app has been restored to work. Please check this log and fix the DCO issue following its instructions. Sorry for the inconvenient 🙏 
DCO log: https://github.com/pipe-cd/pipecd/pull/4940/checks?check_run_id=25870773649

**Comment by khanhtc1202** [comment]
Reopen to trigger DCO check run 👀 But it look like it failed 🤔 
ref: https://github.com/pipe-cd/pipecd/pull/4940/checks?check_run_id=25870773649
cc @chalin

**Comment by chalin** [comment]
@khanhtc1202 - I'll fix this today.

**Comment by chalin** [comment]
Fixed DCO issue. (It's annoying that this can't be fixed via the web i/f for patch PRs 🤷🏼‍♂️. Anyhow, it's done now.)

**Comment by chalin** [comment]
I confirm that data is being processed:

> image

**Comment by khanhtc1202** [comment]
@chalin @nate-double-u thank you all for the support 😄

**Pull request merged**
