### PR TITLE
Add new adopter

### PR DESCRIPTION
**Pull request by mytheta**
**What this PR does / why we need it**:
Canary Inc. as an adopter

**Which issue(s) this PR fixes**:
N/A

**Does this PR introduce a user-facing change?**: 

- **How are users affected by this change**: Not sure.
- **Is this breaking change**: Not sure.
- **How to migrate (if breaking change)**: Not sure.

We are using PipeCD because of its ease of development.

### CODE REVIEW

**Comment by t-kikuc** [comment]
Thank you so much for adopting!!!

Would you please signoff and pass the DCO check? (roughly saying, you need `git commit -s`)
cf. https://github.com/pipe-cd/pipecd/pull/4897/checks?check_run_id=24186548268

**Review by ffjlabo — APPROVED** [review]
@mytheta Thank you so much to add the adopter 👍

**Review by t-kikuc — APPROVED** [review]
Thank you so much 🚀

**Comment by mytheta** [comment]
Thanks, I fixed  🙏 
[403c7eb](https://github.com/pipe-cd/pipecd/pull/4897/commits/403c7eb9a1fb8f640b6c612765c78b37958b2c9a)

**Pull request merged**
