### PR TITLE
Release v0.24.2

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

It seems there were some GitHub errors while publishing the artifacts for the release `v0.24.1`.
So let me bump a new patch version to give it a retry.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
GitHub is not stable now so let's hold this for a while.

**Comment by nakabonne** [comment]
Alright. In that case, do we need get rid of docs/content/en/blog/releases/v0.24.1.md and [this invalid release](https://github.com/pipe-cd/pipecd/releases/tag/v0.24.1)? (Not remove the tag)

**Comment by nghialv** [comment]
> Alright. In that case, do we need to get rid of `docs/content/en/blog/releases/v0.24.1.md` and [this invalid release](https://github.com/pipe-cd/pipecd/releases/tag/v0.24.1)? (not remove the tag)

Right. Let me remove it.

**Comment by khanhtc1202** [comment]
👌 
/lgtm

**Comment by nakabonne** [comment]
🙆 
/approve

**Pull request merged**
