### PR TITLE
Update docs for Google SSO

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:

Google SSO is not yet supported, but some documents describe it.
It's confusing, so I fixed them.

This is because we previously planned the feature but didn't Implement it.

**Which issue(s) this PR fixes**:

Part of #1161

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Review by t-kikuc — COMMENTED** [review]
We should update here too:

https://github.com/pipe-cd/pipecd/blob/395d96e33f87092e18a5af8f93ab039857e99d9b/docs/content/en/docs-dev/feature-status/_index.md?plain=1#L123

**Comment by ffjlabo** [comment]
Thank you! removed in [544c9bb](https://github.com/pipe-cd/pipecd/pull/5044/commits/544c9bb96aad8bb3992cd2d0c28f40e452ed5c73)

**Review by t-kikuc — APPROVED** [review]
Thank you!

**Review by khanhtc1202 — APPROVED** [review]
Thanks 👍

**Pull request merged**
