### PR TITLE
upgrade aws-sdk-go-v2 versions

### LINKED ISSUE #5144: Enable restart policy property for ECS application
**What would you like to be added**:
update github.com/aws/aws-sdk-go-v2/service/ecs to v1.45.0 to set the restart policy in ECS task definitions.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html
https://github.com/aws/aws-sdk-go-v2/blob/release-2024-08-15/service/ecs/CHANGELOG.md#v1450-2024-08-15

**Why is this needed**:
To control the restarting of containers.

### PR DESCRIPTION
**Pull request by tom-256**
**What this PR does / why we need it**:
For enable restart policy in ECS task definitions.

**Which issue(s) this PR fixes**:

Fixes #5144

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

I have confirmed that the ECS restart policy is applied correctly with the following YAML configuration.
```yaml
containerDefinitions:
  - name: test
...
    restartPolicy:
      enabled: true
      ignoredExitCodes:
        - 0
      restartAttemptPeriod: 180
```
The resulting ECS task definition JSON has been registered as follows:
```json
{
...
    "containerDefinitions": [
        {
            "name": "test",
...
            "restartPolicy": {
                "enabled": true,
                "ignoredExitCodes": [
                    0
                ],
                "restartAttemptPeriod": 180
            },
        }
    ],
...
}

### CODE REVIEW

**Review by khanhtc1202 — APPROVED** [review]
Thank you 🚀

**Comment by khanhtc1202** [comment]
@tom-256 please sign the commit follow failed CI instructions 👀

**Review by t-kikuc — COMMENTED** [review]
@tom-256 
Would you fix https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/platformprovider/ecs/diff_test.go#L105 as below?

from: 
```
@@ -17,7 +17,7 @@
```

to:
```
@@ -18,7 +18,7 @@
```


That's because the [test](https://github.com/pipe-cd/pipecd/actions/runs/10734350781/job/29774868112#step:4:232) failed 
since the new field `RestartPolicy` is added and the row number is slided.

**Review by khanhtc1202 — APPROVED** [review]
Nice, thank you 👍

**Comment by t-kikuc** [comment]
Thank you so much, 
I'll test a little by myself and approve!

**Comment by t-kikuc** [comment]
@tom-256 

It turned out that we need to upgrade all `aws-sdk-go-v2` modules, not only ecs.
That's due to breaking changes of the SDK...

Without that, API calls return `not found, ResolveEndpointV2` errors. (especially, ELB and Lambda)

To fix it, would you follow the steps below?


### 1. upgrade all `aws-sdk-go-v2` modules

```
go get -u github.com/aws/aws-sdk-go-v2/...
```

cf. https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1953308268


### 2. fix compile error(s)

e.g.

https://github.com/pipe-cd/pipecd/blob/6b004fa1090cf4d16749eede2843e64631c9da54/pkg/app/piped/platformprovider/ecs/client.go#L508

should be:
``` go
if *rule.IsDefault {
```

This is due to a breaking change https://github.com/aws/aws-sdk-go-v2/pull/2333.

**Comment by t-kikuc** [comment]
I'll continue on https://github.com/pipe-cd/pipecd/pull/5241

**Pull request closed without merging**
