### PR TITLE
Add a metrics to know deployment count of each project

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
Thank you. 🚀 
Will you update the dashboard with another PR?

**Review by khanhtc1202 — APPROVED** [review]
Nice 👍

**Comment by nghialv** [comment]
> Thank you. 🚀 Will you update the dashboard with another PR?

Yep.

**Comment by knanao** [comment]
Okey, thanks

**Review by knanao — APPROVED** [review]

**Pull request merged**
