### PR TITLE
Run make gazelle for eventwatcher

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nakabonne** [comment]
Good catch!

But actually it will be added again on: https://github.com/pipe-cd/pipecd/pull/3124/files#diff-60908ffb7e37bfc3692d8c4cace4be91d53bccf9a549fb91ea30b70387abd9cfR32-R34

**Comment by nakabonne** [comment]
Merge this then that PR will not be able to be built, so would you mind closing this?

**Comment by knanao** [comment]
Oh, I see. Sorry🙇

**Comment by nakabonne** [comment]
Nope, well noticed!

**Pull request closed without merging**
