### PR TITLE
Upgrade aws-sdk-go-v2

### LINKED ISSUE #5144: Enable restart policy property for ECS application
**What would you like to be added**:
update github.com/aws/aws-sdk-go-v2/service/ecs to v1.45.0 to set the restart policy in ECS task definitions.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html
https://github.com/aws/aws-sdk-go-v2/blob/release-2024-08-15/service/ecs/CHANGELOG.md#v1450-2024-08-15

**Why is this needed**:
To control the restarting of containers.

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

Mainly:
- upgraded `aws-sdk-go-v2` especially `aws-sdk-go-v2/service/ecs`

Associated tasks:
- upgraded other `aws-sdk-go-v2/**/*` to solve the breaking change.
     - cf. https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1953308268
- fixed compile errors caused by the breaking change.
     - in `pkg/filestore/s3/s3.go` and `pkg/app/piped/platformprovider/ecs/client.go`
     - cf. https://github.com/aws/aws-sdk-go-v2/pull/2333
- fixed a test since`RestartPolicy` is added and the row number slided
     - in `pkg/app/piped/platformprovider/ecs/diff_test.go`

**Which issue(s) this PR fixes**:

Fixes #5144

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by t-kikuc** [comment]
reopen for rerun snyk test

**Comment by t-kikuc** [comment]
re:reopen for rerun snyk test

**Review by khanhtc1202 — APPROVED** [review]
LGTM 👍

**Review by Warashi — APPROVED** [review]
👍🏻

**Pull request merged**
