### PR TITLE
[doc] Fix indents of the pprof page

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

- Fix indents of the procedures
    - especially, `2. Get the Cpi Profile` was merged with the previous line.

    image

- Add one 'a'

**Which issue(s) this PR fixes**: no

**Does this PR introduce a user-facing change?**: no

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Screenshot 2024-02-06 at 11 58 23

some tabs mixes with spaces @t-kikuc

**Comment by t-kikuc** [comment]
> Screenshot 2024-02-06 at 11 58 23
> some tabs mixes with spaces @t-kikuc

Thanks, I fixed it

**Comment by ffjlabo** [comment]
@t-kikuc Is this still miexd?
_doc__Fix_indents_of_the_pprof_page_by_t-kikuc_·_Pull_Request__4776_·_pipe-cd_pipecd

**Comment by t-kikuc** [comment]
Sorry, I fixed. (by removing the last line)

Besides, I fixed the doc of v0.46.x too.

**Review by khanhtc1202 — APPROVED** [review]
🚀

**Comment by khanhtc1202** [comment]
@ffjlabo Please

**Review by ffjlabo — APPROVED** [review]
🚀

**Pull request merged**
