### PR TITLE
Update quickstart/_index.md

### PR DESCRIPTION
**Pull request by clubanderson**
fixed some grammar issue

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by t-kikuc** [comment]
@clubanderson 
Thank you for your great contribution!

Would you please sign off and pass the DCO check?
cf. https://github.com/pipe-cd/pipecd/pull/4893/checks?check_run_id=24111264579

**Review by t-kikuc — CHANGES_REQUESTED** [review]
@clubanderson 
Thank you so much for your corrections! 🙏 

Would you copy your changes to other versions by the following command?
That's because grammatical corrections should be applied to all versions. 
(We're sorry for the unclear process...)

```sh
find docs/content/en/*/quickstart/_index.md -type f -exec sed -i '' \
-e 's/on your browser/in your browser/g' \
-e 's/logged in successfully/successfully logging in/g' \
-e 's/at `piped` settings tab/at the `piped` settings tab/g' \
-e 's/will keep running/will run continuously/g' \
-e 's/will not lost/will not be lost/g' \
-e 's/Above are all we need/Above is all that is necessary/g' \
-e 's/deployment would be complete automatically to/deployment is complete and will automatically/g' \
 {} \;
```

It will copy the changes to:

- docs/content/en/docs-dev/quickstart/_index.md
- docs/content/en/docs-v0.39.x/quickstart/_index.md
- docs/content/en/docs-v0.40.x/quickstart/_index.md
- docs/content/en/docs-v0.41.x/quickstart/_index.md
- docs/content/en/docs-v0.42.x/quickstart/_index.md
- docs/content/en/docs-v0.43.x/quickstart/_index.md
- docs/content/en/docs-v0.44.x/quickstart/_index.md
- docs/content/en/docs-v0.45.x/quickstart/_index.md
- docs/content/en/docs-v0.46.x/quickstart/_index.md

After you do it, I'd like to approve🚀

**Review by t-kikuc — APPROVED** [review]

**Review by t-kikuc — CHANGES_REQUESTED** [review]
plz DCO 🙏

**Comment by clubanderson** [comment]
I signed the PR and updated all versions. I do not know what else is blocking this PR now. Please advise

**Review by t-kikuc — APPROVED** [review]
Thank you so much!!!!

**Comment by t-kikuc** [comment]
@clubanderson 
Thank you for signing and coping your changes!!
This PR will be merged after another reviewer approves. 
You do not need to do something else:)

**Review by ffjlabo — APPROVED** [review]
Thank you so much :)

**Pull request merged**
