### PR TITLE
Add rfc for ECS not under ELB (Issue#4616)

### LINKED ISSUE #4616: Support progressive delivery for ECS apps using Service Discovery
**What would you like to be added**:

Support ECS apps progressive delivery using only ECS components (without ALB configuration)

**Why is this needed**:

Currently, to perform progressive delivery for ECS applications, we need users to prepare ALB targetgroups. For some usecases, users' tasks may not directly accept/handle traffic from the ALB but via other tasks/components which leads to the inability to perform progressive delivery strategies.

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

To support progressive delivery for ECS without ELB.

It's not so big change, but I think ECS users will be affected in the future.

**Which issue(s) this PR fixes**:

Part of #4616

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**: No
- **Is this breaking change**:  No
- **How to migrate (if breaking change)**:  No

### CODE REVIEW

**Comment by t-kikuc** [comment]
I'll modify DCO and `Target Version: (s1.x / 2.x)` soon today.

**Comment by khanhtc1202** [comment]
@t-kikuc please sign the commit with `git commit -s`

**Comment by t-kikuc** [comment]
@khanhtc1202  thank you.
I signed and passed DCO check.

**Comment by t-kikuc** [comment]
This is the blue/green deployment flow in RFC (GitHub fails to render):

bluegreen

**Review by khanhtc1202 — APPROVED** [review]
Look great, let's gooo 🚀

**Pull request merged**
