### PR TITLE
Add description for AWS Lambda/ECS credentialsFile

### PR DESCRIPTION
**Pull request by chaspy**
**What this PR does / why we need it**:
When I try to Deploy Lambda, I didn't know in which format to put this file.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chaspy** [comment]
Hello, maintainers.

First, could you please review the details of this change?

And I found the following documentation files.
Could you please let me know which file I should update?

```
$ git grep CloudProviderLambdaConfig | grep docs | cut -d ':' -f1     ?[chaspy/update-credentials-file]
docs/content/en/docs-dev/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.18.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.20.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.21.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.22.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.23.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs-v0.24.x/operator-manual/piped/configuration-reference.md
docs/content/en/docs/operator-manual/piped/configuration-reference.md
```

**Comment by nghialv** [comment]
@chaspy Thank you for your PR.
Could you make it ready to be reviewed since currently it is under the Draft mark?

@khanhtc1202 PTAL on this.

**Comment by khanhtc1202** [comment]
@chaspy nice catch 😀 
for the question, please update content under: /docs, /docs-dev and /docs-v0.24.0 for this change.

**Comment by khanhtc1202** [comment]
Nice work, thank you 🙌 
/approve

**Pull request merged**
