### PR TITLE
Fix plan-preview action to hide comment

### PR DESCRIPTION
**Pull request by Hosshii**
**What this PR does / why we need it**:
#3126 does not hide comment. This pr fixes bug and update version

**Which issue(s) this PR fixes**:

Fixes #3126

**Does this PR introduce a user-facing change?**:

```release-note
Fix the bug of plan-preview action that caused preview comments not to be hidden
```

### CODE REVIEW

**Comment by nghialv** [comment]
@Hosshii Nice catch! Thank you.

Could you update the PR's description? That note block will be used to generate release notes which will be read by our end users.

`Does this PR introduce a user-facing change?:`

```
Fix the bug of plan-preview action that caused preview comments not to be hidden
```

**Comment by Hosshii** [comment]
I fixed.
Thank you!

**Comment by nghialv** [comment]
Great job. Thank you.
/approve

**Pull request merged**
