### PR TITLE
Sort trailers to ensure the order

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does**:

Sort trailers before commit with them to ensure the order.

**Why we need it**:

**Which issue(s) this PR fixes**:

Part of https://github.com/pipe-cd/pipecd/issues/5028

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by khanhtc1202** [comment]
@ffjlabo Go build and test failed, maybe caused by the CI go version 👀

**Comment by ffjlabo** [comment]
@khanhtc1202 Sorry, it seems that these feature are supported from Go 1.23. So I will rewrite it with Go 1.22 syntax for now.

**Comment by ffjlabo** [comment]
@khanhtc1202 Updated at [6594052](https://github.com/pipe-cd/pipecd/pull/5334/commits/6594052f1747f001c02ac8617b893e92c6db971c) 🙏

**Review by Warashi — APPROVED** [review]
LGTM

**Review by t-kikuc — APPROVED** [review]

**Pull request merged**
