### PR TITLE
Remove deprecated fields from models

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

This PR removes several deprecated fields from pipecd's models.
- GITHUB_ENTERPRISE enum value as ProjectSSOConfig_Provider (marked 2 years ago: [blame](https://github.com/pipe-cd/pipecd/blame/master/pkg/model/project.proto#L72-L74))
- handled field in event model (marked 5 months ago: [blame](https://github.com/pipe-cd/pipecd/blame/master/pkg/model/event.proto#L44) - before v0.26.0)
- config_path field in ApplicationGitPath type (marked 2 years ago: [blame](https://github.com/pipe-cd/pipecd/blame/master/pkg/model/common.proto#L41))

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Can you list the time when each of them was deprecated?

**Comment by khanhtc1202** [comment]
> Can you list the time when each of them was deprecated?

Updated the PR description to add time when we marked it as deprecated

**Comment by nghialv** [comment]
Thank you.

**Review by nghialv — APPROVED** [review]
Nice.

**Review by knanao — APPROVED** [review]
Here you go!

**Pull request merged**
