### PR TITLE
Remove environment concept from web view

### LINKED ISSUE #3193: Remove web components for Environment
**What would you like to be added**:

Since the environment concept was already deprecated.

**Why is this needed**:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3193 

**Does this PR introduce a user-facing change?**:

```release-note
Remove Environment concept from web view
```

### CODE REVIEW

**Comment by nghialv** [comment]
Great work!
Definitely, this will be included in `v0.26.0`. 
However, before that, I think we should release `v0.25.1` which contains

* Monthly update for this month and it also contains migration guide for external users
* Redesign ADD FROM SUGGESTIONS form and make it as default ([#3196](https://github.com/pipe-cd/pipecd/pull/3196))
* Refine Event list UI ([#3205](https://github.com/pipe-cd/pipecd/pull/3205))
* Fix to decrypt secret for CloudRun's drift detector ([#3200](https://github.com/pipe-cd/pipecd/pull/3200))
* Handle unavalable piped to avoid blocking plan-preview ([#3181](https://github.com/pipe-cd/pipecd/pull/3181))

So how about holding this for a while, what do you think?

**Comment by khanhtc1202** [comment]
for sure 👍 plz go ahead
/hold

**Comment by nghialv** [comment]
Okay. Let's unhold this and merge to avoid conflict.
/lgtm

**Comment by khanhtc1202** [comment]
Thank you 🙆‍♂️ 
/hold cancel

**Comment by knanao** [comment]
Cool!
/approve

**Pull request merged**
