### PR TITLE
Fix the type assertion for event watcher cache

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by nghialv — APPROVED** [review]
Nice catch!

**Comment by knanao** [comment]
@nghialv @khanhtc1202 
Sorry, I fixed some points, so please review this again when you guys have time.

**Review by nghialv — APPROVED** [review]
Sure.

**Review by khanhtc1202 — APPROVED** [review]
Nice catch

**Pull request merged**
