### PR TITLE
Fix command-line-tool.md: GCR to GHCR

### PR DESCRIPTION
**Pull request by Reimei1213**
**What this PR does**:

We migrated from GCR to GHCR, but the documentation still mentioned GCR, so I updated it accordingly.

**Why we need it**:

We moved to use ghcr instead

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Nice catch, thanks @Reimei1213 👍
Could you update the `/docs-dev` version of this docs too? (same file name but under the docs-dev dir)

**Comment by Reimei1213** [comment]
@khanhtc1202 
I've corrected it, please check 🙇

**Review by t-kikuc — APPROVED** [review]
Thank you so much!!

**Review by khanhtc1202 — APPROVED** [review]
Thank you 👍

**Pull request merged**
