### PR TITLE
Add the application ID to the application detail page

### LINKED ISSUE #4810: Show Application ID on the application page
**What would you like to be added**:

It would be nice to show an application ID with a copiable field on the application page.

PipeCD

Cursor_と_PipeCD

**Why is this needed**:

It is helpful to share the application ID for debugging.

### PR DESCRIPTION
**Pull request by dgannon991**
**What this PR does / why we need it**: It displays the application ID on the application details page with a handy copy button.

**Which issue(s) this PR fixes**:

Fixes #4810

**Does this PR introduce a user-facing change?**: Yes

- **How are users affected by this change**: Additional information in the UI only
- **Is this breaking change**: No
- **How to migrate (if breaking change)**: N/A

### CODE REVIEW

**Comment by ffjlabo** [comment]
@dgannon991 Thank you for your contribution!
Could you sign off your commit using `git commit -s` ?
refs: https://github.com/pipe-cd/pipecd/blob/master/CONTRIBUTING.md#contributor-license-agreement

**Comment by dgannon991** [comment]
@ffjlabo - done, sorry about that, I very rarely use this laptop, and obviously forgot to set it up properly :D

**Comment by ffjlabo** [comment]
@dgannon991 
It seems that the commit is not singed off👀

Can you try the commands below?

git commit -a --amend
git push -f

**Comment by dgannon991** [comment]
Sorry, I'd ensured that the commit was signed by my PGP key, but hadn't noticed it was missing the "signed off" part of the commit message. Apologies. That should be fixed now, as well as the linting issue reported on the pipeline! I promise the next one I do will be smoother :)

**Comment by ffjlabo** [comment]
@dgannon991 No worries 👍 
Thank you so much. Successfully signed off!!

Also, sorry for the late comment 🙏 
It would be nice to move the application ID before the row `kind` for clarity. 

PipeCD

 I will approve this PR after fixing it :)

**Comment by khanhtc1202** [comment]
@dgannon991 There is a lint error occurred 👀 You can run `make lint/web FIX=true` in your local in order to fix that 😄

**Comment by dgannon991** [comment]
Oh this is really embarrassing! It was meant to be such a simple item to start with, and I just can't seem to get it right :D Hopefully now we're there!

**Comment by khanhtc1202** [comment]
No worries; it's our fault for not making it clear. But we're going well. Thanks a lot for the commits 🙌

**Review by khanhtc1202 — APPROVED** [review]
Nice improvement, thanks 🚀

**Review by ffjlabo — APPROVED** [review]
Great work! Thank you 🚀

**Pull request merged**
