### PR TITLE
Show updated_at instead of deployed_at in the application list page

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
🙌

**Comment by khanhtc1202** [comment]
You can use `yarn --cwd web lint:fix` to fix the lint which pass the CI lint check

**Comment by nghialv** [comment]
Sure. I have just lint-ed the changes.

**Review by khanhtc1202 — APPROVED** [review]
🙌

**Review by knanao — APPROVED** [review]
Let's go!

**Pull request merged**
