### PR TITLE
Register otel TracerProvider to send traces

### PR DESCRIPTION
**Pull request by Warashi**
**What this PR does / why we need it**:

This PR implements the creation of otel TracerProvider and sets the created one as default.

**Which issue(s) this PR fixes**:

Part of #4977 

**Does this PR introduce a user-facing change?**: No

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by khanhtc1202** [comment]
@Warashi There is an error on Snyk security check, could you check 🙏

**Comment by Warashi** [comment]
Thank you. I'll check it later.

**Review by ffjlabo — APPROVED** [review]
LGTM 🚀 and just left the nit memo

**Review by khanhtc1202 — APPROVED** [review]
LGTM 👍

**Pull request merged**
