### PR TITLE
Update Automated configuration drift detection for CloudRun feature status

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
💯 
/lgtm

**Comment by khanhtc1202** [comment]
btw, I think the PR title should be `Update Automated configuration drift detection for CloudRun feature status` @knanao

**Comment by nghialv** [comment]
Thank you.
/approve

**Pull request merged**
