### PR TITLE
Add EnableApplication rpc for grpc api service

### PR DESCRIPTION
**Pull request by kurochan**
**What this PR does / why we need it**:
Support enable application operation through grpc api.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Add EnableApplication rpc for grpc api service
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Hi @kurochan thanks for your contribution 😁
Could you share the purpose of this PR? Since this PR only add rpc to grpc api (backend to handle pipectl request) we need to add pipectl imp as the caller side if you want to use this rpc 👀

**Comment by kurochan** [comment]
@khanhtc1202 I'm trying to developing terraform provider for pipecd. In the process of that, I found there are no function to enable applications.

Should I implement pipectl command in this PR?

**Comment by khanhtc1202** [comment]
> I'm trying to developing terraform provider for pipecd. In the process of that, I found there are no function to enable applications.

I see, if you plan to connect to this rpc directly (not via pipectl) then it's fine to not implement pipectl command.

**Review by khanhtc1202 — APPROVED** [review]
lgtm 👌

**Pull request merged**
