### PR TITLE
Add link to Tutorial on the header bar

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

I replaced the link to Tutorial as we published [the tutorial](https://github.com/pipe-cd/tutorial).

The tutorial would be the best entrance for those who got interested in PipeCD.

**Does this PR introduce a user-facing change?**: N/A

**Image**

current:
image

after this commit: 
image

### CODE REVIEW

**Comment by khanhtc1202** [comment]
@t-kikuc How about adding `Tutorial` as a button next to the header Documentation and before Blog (below image red-cycled area)? I think it's a better place for its purpose. Also, we can update the current `Quickstart` page and add Note/Link to the Tutorial repo as another way for a detailed start for users

Screenshot 2024-06-06 at 9 06 18

**Comment by t-kikuc** [comment]
@khanhtc1202 
Thanks, I'll create the button.

1. What do you think about this change? Not necessary?
[5921276](https://github.com/pipe-cd/pipecd/pull/4937/commits/59212769025f07a9d404485880fd39d491a7ff0a)



2. >we can update the current Quickstart page and add Note/Link to the Tutorial repo as another way for a detailed start for users

    -> I'll do it in another PR.

**Comment by khanhtc1202** [comment]
> What do you think about this change? Not necessary?

@t-kikuc I don't think we should remove the Quickstart button at the moment. There are some reasons for that from my point of view
1. I think we should not redirect users to another site (not pipecd.dev) for the purpose of quickstart
2. The Tutorial button in the header will be shown on all pages of the site, which I think is a better place and suits its purpose. We will have a header showing ( Documentation - Tutorial - Blogs - ... )

**Comment by khanhtc1202** [comment]
Sorry, I missed click the close PR button 🙏

**Comment by t-kikuc** [comment]
@khanhtc1202 
I fixed as below!
`Tutorial` button will also be shown other than the top page.
image
image

**Review by khanhtc1202 — APPROVED** [review]
Nice added 🙌

**Review by ffjlabo — APPROVED** [review]
🚀

**Comment by t-kikuc** [comment]
> we can update the current Quickstart page and add Note/Link to the Tutorial repo as another way for a detailed start for users

-> I'll do it in another PR.

I opened a PR https://github.com/pipe-cd/pipecd/pull/4964 for that.

**Pull request merged**
