### PR TITLE
Correct the screenshot in quickstart

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
I think we should only change the `/docs-dev` version and keep the `add-from-git` image since old versions docs still us that 👀

**Comment by nghialv** [comment]
> I think we should only change the `/docs-dev` version and keep the `add-from-git` image since old versions docs still use that 👀

Nice catch! Since "Add From Suggestions" was already released from v0.25.1 so let's me keep the old image and revert changes of anything before "docs-v0.25.x".

**Comment by nghialv** [comment]
@khanhtc1202 Updated!

**Comment by khanhtc1202** [comment]
Nice, thank you
/approve

**Pull request merged**
