### PR TITLE
Fix broken links due to change of repository name

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by knanao** [comment]
It might be better to rename here as well.
https://github.com/pipe-cd/pipecd/blob/master/NOTICE.txt#L1

**Comment by nghialv** [comment]
@knanao Nice catch! Let me fix it.

**Comment by nghialv** [comment]
Let me merge this to fix broken links in our docs.
/approve

**Pull request merged**
