### PR TITLE
Run tests in parallel for pkg/app/piped

### PR DESCRIPTION
**Pull request by Hosshii**
**What this PR does / why we need it**:
Add `t.Parallel` to execute tests in parallel. And delete unused test files.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Hosshii** [comment]
This is more faster than others ([add t.parallel to all test](https://github.com/pipe-cd/pipecd/pull/3384) and [add t.parallel to slow test](https://github.com/pipe-cd/pipecd/pull/3386)).
So could you review this PR?

**Review by knanao — COMMENTED** [review]
Nice catch!
Let me check one point.
If we run cases of table driven tests sequentially, the tests will be extremely slow?

**Comment by Hosshii** [comment]
I think If each case of the table is slow, parallelization would speed it up. Otherwise, the cost of parallelization would be more expensive.

**Comment by Hosshii** [comment]
I wrote these tests before https://github.com/pipe-cd/pipecd/pull/3370#discussion_r823411355. So these tests uses `t.Parallel` in sub tests. But it might be good to remove it.

**Comment by knanao** [comment]
Thanks.
It seems good to decide the coding policy of our team and decide which one to use.

> we can use parallel on test function level or test cases level only, wdyt?

That's why, let we apply this!

**Comment by Hosshii** [comment]
Thank you!  I removed sub-level t.parallel

**Comment by knanao** [comment]
Awesome!
/lgtm

**Comment by khanhtc1202** [comment]
Here you go 🙌 
/approve

**Pull request merged**
