### PR TITLE
Add status of failing load application config

### PR DESCRIPTION
**Pull request by funera1**
**What this PR does / why we need it**:
Add status for load Application failure and added icon for that status.

**Which issue(s) this PR fixes**:

Fixes part of #4149 

**Does this PR introduce a user-facing change?**:
Icon view (As an example, I applied an invalid config status icon instead by the synced status icon.)
image
```release-note
NONE
```

### CODE REVIEW

**Comment by funera1** [comment]
@knanao 
Please review my code when you have time.

**Comment by khanhtc1202** [comment]
Would like to use this mark ⚠️ since the current icon in the picture has quite same color with the out of sync icon 👀

**Comment by funera1** [comment]
@khanhtc1202 
Thank you for nice comment. Would you want to use this icon if you add for example WARNING status.
If that problem is ok, I agree to use this icon:smiley:.

**Comment by khanhtc1202** [comment]
@funera1 Got your point. That warning icon maybe mean to some generic warning for sure. But from the users point of view, `warning: application configuration loaded failed` should be treated as a warning, isn't it? 🤔

**Comment by funera1** [comment]
@khanhtc1202 
I understand. That's certainly true. I will apply that icon. Thanks.

**Comment by funera1** [comment]
Changed icon view:smiley:
image

**Comment by khanhtc1202** [comment]
@funera1 how about the text next to it, should not be `Synced`, right? 🤔

**Comment by khanhtc1202** [comment]
@funera1 how about the text next to it, should not be `Synced`, right? 🤔

**Comment by khanhtc1202** [comment]
@funera1 how about the text next to it, should not be `Synced`, right? 🤔

**Comment by funera1** [comment]
@khanhtc1202 
I'm trying with Synced status instead because I can't get INVALID_CONFIG until this PR version of control plane is released.

**Comment by khanhtc1202** [comment]
Oops, got your point, in that case, it's okay to keep it in single PR like this. Thanks 🙌

**Review by knanao — APPROVED** [review]

**Pull request merged**
