### PR TITLE
Fix a bug that not allowed users can approve the WAIT_APPROVAL stage

### LINKED ISSUE #2550: Ensure only users which mentioned in the WAIT_APPROVAL approvers are able to approve the stage
**What happened**:

Currently, users who are not be listed in the WAIT_APPROVAL approvers configuration are able to approve the stage.

ref: https://pipecd.dev/docs/user-guide/adding-a-manual-approval/

Note: according to the docs we have
> In case the approvers field was not configured, anyone in the project who has Editor or Admin role can approve the deployment pipeline.

**What you expected to happen**:

In case the approvers field is configured, only people listed in that field are able to approve the stage.

**How to reproduce it**:

**Environment**:
- `piped` version: 0.18.0
- `control-plane` version: 0.18.0
- Others:

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2550 

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug that not allowed users can approve the WAIT_APPROVAL stage
```

### CODE REVIEW

**Comment by nakabonne** [comment]
@ono-max Feel free to mention instead of the review request 👍  (honestly, I don't have any channel to know getting the review request because ignoring this repository for a long time)

image

**Comment by ono-max** [comment]
@nakabonne 

Thanks, I've updated it 👍

**Comment by nakabonne** [comment]
Helps a lot!
/lgtm

**Comment by nakabonne** [comment]
@ono-max Can you change the changelog if you agree with https://github.com/pipe-cd/pipe/pull/2602#issuecomment-938323645 ?

**Pull request merged**
