### PR TITLE
Remove sealsecret code

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Deprecated feature, use SecretManagement instead
https://pipecd.dev/docs/user-guide/managing-application/secret-management/

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by knanao** [comment]
@khanhtc1202 
Sorry, plz rebase this from a master branch.

**Review by knanao — COMMENTED** [review]
Thank you!
It's enough time passed to un-support this feature, and let's not forget to add a breaking change section to the next release note.
https://github.com/pipe-cd/pipecd/blob/master/docs/content/en/blog/releases/v0.10.0.md#deprecated-features

btw, how about changing `Does this PR introduce a user-facing change?` to announce this breaking change?

**Comment by khanhtc1202** [comment]
@knanao Good catch, but as far as I know from the codebase, looks like the SealedSecret manifest kind are not being used (un-supported) for a while already means that users can not use it already, so I guess we can ignore that from the release note. This PR should be counted as removing unused code, wdyt?

**Review by knanao — APPROVED** [review]
@khanhtc1202 
Oh, I see. Nice catch!

**Pull request merged**
