### PR TITLE
Revert "Revert "Change diff detail's header""

### PR DESCRIPTION
**Pull request by khanhtc1202**
Reverts pipe-cd/pipecd#4236

### CODE REVIEW

**Comment by knanao** [comment]
I feel this should be updated by @funera1 with another PR instead of this revert PR.

**Comment by khanhtc1202** [comment]
> I feel this should be updated by @funera1 with another PR instead of this revert PR.

I don't think so since this fix panic on master, `Out of sync` issue should be carefully fix later 👀

**Comment by khanhtc1202** [comment]
Or another option to resolve panic on master is to revert this https://github.com/pipe-cd/pipecd/pull/4202
wdyt?

**Comment by knanao** [comment]
@khanhtc1202 
> We should resolve panic on master branch to not block other works. wdyt?
Right, but I wonder what the cause of the panic?

**Comment by khanhtc1202** [comment]
okay let's revert #4202 👍
@knanao @funera1

**Review by knanao — COMMENTED** [review]
@khanhtc1202 
Okay, that's why let's close this.

**Comment by funera1** [comment]
@knanao @khanhtc1202 
I reverted #4202, so please you check it.

**Pull request closed without merging**
