### PR TITLE
Make it clear to attach IAM policies to ECS task-role

### PR DESCRIPTION
**Pull request by t-kikuc**
**What this PR does / why we need it**:

Make it clear which role to attach IAM policies to because ECS's `task-role` and `task-execution-role` are confusing.

### CODE REVIEW

**Review by khanhtc1202 — APPROVED** [review]
👍

**Review by Warashi — COMMENTED** [review]
How about removing this line?
https://github.com/pipe-cd/pipecd/blob/7ca5c05b57b7f8e25006b708be799b2fb44223ac/docs/content/en/docs-dev/installation/install-piped/required-permissions.md?plain=1#L49

**Comment by t-kikuc** [comment]
@Warashi 

> How about removing this line?
> 
> https://github.com/pipe-cd/pipecd/blob/7ca5c05b57b7f8e25006b708be799b2fb44223ac/docs/content/en/docs-dev/installation/install-piped/required-permissions.md?plain=1#L49

It’s mandatory.
When a piped creates a new task, the piped needs to pass task-execution-role to the task.

**Comment by Warashi** [comment]
> It’s mandatory.
> When a piped creates a new task, the piped needs to pass task-execution-role to the task.

Sorry, I misread.

As I understood, the `Resource` field at this line does not mean the role to which we add permission but the role we use to run the tasks.
So we need this line.

**Review by Warashi — APPROVED** [review]
LGTM

**Pull request merged**
