### PR TITLE
Terraform module version optional

### LINKED ISSUE #3531: Error planning deployment of Terraform kind in case of missing module version field
**What happened**:

> Unable to plan the deployment (/tmp/workspace2033101394/e14d4690-0780-4036-bc8e-375c4e0e34fa-planner-4078311696/target-deploysource/deploysource2606679743/repo-1/xxxxx/yyyyy.tf Missing required argument; The argument "version" is required, but no definition was found., and 2 other diagnostic(s)

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version: v0.27.2
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Make the Terraform module version field optional

**Which issue(s) this PR fixes**:

Fixes #3531

**Does this PR introduce a user-facing change?**:

```release-note
Fix error unable to plan deployment of kind Terraform in case of missing module version argument
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
Nice catch!
/lgtm

**Comment by nghialv** [comment]
Maybe we have to get rid of this validation as well.
https://github.com/pipe-cd/pipecd/blob/master/pkg/model/common.proto#L88

**Comment by khanhtc1202** [comment]
> Maybe we have to get rid of this validation as well. https://github.com/pipe-cd/pipecd/blob/master/pkg/model/common.proto#L88

Thanks for comment, addressed by https://github.com/pipe-cd/pipecd/pull/3530/commits/8d061cc3791c4a7771eda0ba39c7013077dadc94

**Comment by nghialv** [comment]
Nice catch!
/approve

**Review by knanao — COMMENTED** [review]
/cangelog

**Pull request merged**
