### PR TITLE
Fix pod config for envoy upstreaming termination error

### LINKED ISSUE #1349: Fix envoy config and pod lifetime to avoid error while rolling out pipecd
**What happened**:

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by kevin55156**
**What this PR does / why we need it**:
Add preStop to api-server's manifest to enable envoy to know server is terminating

**Which issue(s) this PR fixes**:

Fixes #1349 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by knanao** [comment]
@kevin55156 
I guess this's a connection error when rolling out, so I'm wondering whether this time sleep will resolve that or not.

wdyt?

**Comment by knanao** [comment]
We've already set 30s as `gracePeriod` at the application layer, but `terminationGracePeriodSeconds` is not set, which means the default value `30s` is used.

Hence, I feel this will not work as we expected, wdyt?
So, how about setting `terminationGracePeriodSeconds` to 60s.

https://github.com/pipe-cd/pipecd/blob/master/cmd/pipecd/server.go#L106

**Comment by kevin55156** [comment]
> We've already set 30s as `gracePeriod` at the application layer, but `terminationGracePeriodSeconds` is not set, which means the default value `30s` is used.
> 
> Hence, I feel this will not work as we expected, wdyt? So, how about setting `terminationGracePeriodSeconds` to 60s.
> 
> https://github.com/pipe-cd/pipecd/blob/master/cmd/pipecd/server.go#L106

I have changed `terminationGracePeriodSeconds` , but this error was not be solved. Maybe this error is due to that pod response stop before pod's status changed to be 'terminating'

**Comment by knanao** [comment]
@kevin55156 
Thank you for your investigation.
From your comments, I feel this looks fine.

LGTM

**Review by khanhtc1202 — APPROVED** [review]
🙌

**Pull request merged**
