### PR TITLE
Remove the annotation for pipecd.dev/resource-key

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does / why we need it**:

Remove the annotation `pipecd.dev/resource-key` because it is no longer used.

**Which issue(s) this PR fixes**:

Part of #4269

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**: -
- **Is this breaking change**: no
- **How to migrate (if breaking change)**: no

### CODE REVIEW

**Review by Warashi — COMMENTED** [review]
The changes themselves seem good.
By the way, will users face a lot of Out of Sync after merging this PR?
So I think this is a change that needs to be announced carefully.

**Comment by ffjlabo** [comment]
@Warashi 
Thank you for the opinion!

I think the annotation is added when creating or updating the resource.
The old resource holds the annotation at the time even though this PR is merged.
So it does not affect the users.

But I will check the behavior just in case👍

**Review by khanhtc1202 — APPROVED** [review]
LGTM 👍

**Comment by khanhtc1202** [comment]
Let's close this due to the revert PR #4997 4997

**Pull request closed without merging**
