### PR TITLE
Do not show the detail block in plan-preview comment when its content was empty

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
Let me check https://github.com/pipe-cd/pipecd/pull/3458 behavior.
That's why I temporary hold this until done that.
/hold

**Comment by knanao** [comment]
Thank you🙌 
/lgtm

**Comment by khanhtc1202** [comment]
Nice catch
/approve

**Pull request merged**
