### PR TITLE
Refine web console UI/UX related to show Piped configuration feature

### PR DESCRIPTION
**Pull request by Szarny**
**What this PR does / why we need it**:

1. Expand dialog width and add syntax highlighter for yaml
image

3. Make "Show the configuration" item disabled when piped config hasn't loaded yet.
image

**Which issue(s) this PR fixes**:

Fixes partially #3712 

**Does this PR introduce a user-facing change?**:

```release-note
Refine web console UI/UX related to show Piped configuration feature
```

### CODE REVIEW

**Comment by Szarny** [comment]
hold: https://github.com/pipe-cd/pipecd/pull/3716

**Review by nghialv — APPROVED** [review]
Looks nice.

**Comment by Szarny** [comment]
#3722 merged

**Comment by knanao** [comment]
Nice improvement!

**Review by knanao — APPROVED** [review]

**Pull request merged**
