### PR TITLE
Upload hugo image to use 0.92.1

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:
This PR is separated by https://github.com/pipe-cd/pipecd/pull/3188.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
nits, should we update the docs on this PR?

**Comment by knanao** [comment]
In my opinion, this PR just push docker image.
Therefore, it doesn't need.

**Comment by khanhtc1202** [comment]
> In my opinion, this PR just push docker image. Therefore, it doesn't need.

Sure 👍  /lgtm

**Comment by nghialv** [comment]
Nice.
/approve

**Pull request merged**
