### PR TITLE
Remove environment store

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

This is a part of removing the Environment concept from PipeCD project. I planned to do it later but looks like we have to do extra work for keeping this unused store, so I remove the EnvironmentStore and every place where its interface is used. The Environment model and APIs related to that model still exist and will be removed later.

**Which issue(s) this PR fixes**:

Part of #3221 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
Before this, I think we have to remove it from `pipectl` and `piped` to ensure that no one is using any RPC related to it.

**Comment by khanhtc1202** [comment]
That's true, lets me hold this pull and remove environment-related parts in pipectl and piped first.
/hold

**Comment by khanhtc1202** [comment]
Since PR #3229 is merged, and there is no place that calls Environment-related gRPC directly from pipectl source, I think it's safe to un-hold this pull, PTAL when you guys have time @nghialv @knanao 
/hold cancel

**Comment by knanao** [comment]
Looks good!
/lgtm

**Comment by nghialv** [comment]
> Since PR #3229 is merged, and there is no place that calls Environment-related gRPC directly from pipectl source, I think it's safe to un-hold this pull, PTAL when you guys have time @nghialv @knanao

I think we still have to hold this PR. The #3229 is merged but it is not being released yet. That means our users still using the old Pipeds.
Once this PR got merged, all old Pipeds will face the error due to the lack of those gRPC implementations. So we have to wait until all our users move their Pipeds to the upcoming version first.
What do you think?

**Comment by knanao** [comment]
Oh, I got you. That's make sense.

**Comment by khanhtc1202** [comment]
> > Since PR #3229 is merged, and there is no place that calls Environment-related gRPC directly from pipectl source, I think it's safe to un-hold this pull, PTAL when you guys have time @nghialv @knanao
> 
> I think we still have to hold this PR. The #3229 is merged but it is not being released yet. That means our users still using the old Pipeds. Once this PR got merged, all old Pipeds will face the error due to the lack of those gRPC implementations. So we have to wait until all our users move their Pipeds to the upcoming version first. What do you think?

oops, I get your point. Mostly, the environment-related removed code from piped source is used by notification feature, but for older version piped, it may have something more than that, it's safer to ensure at least all our direct customers update their Piped to the latest version (the one that not yet being released). Tbh, I make this PR cause I don't want to keep this unneeded EnvironmentStore as part of the server code before I start refactoring API's stub, but looks like there is no another way for that. I'm thinking about closing this pull and refactoring EnvironmentStore (remove UpdateEnvironment function) as I did with others, wdyt 🤔

**Comment by khanhtc1202** [comment]
I will close this since there will be a lot of conflicts until this is merged (we have some already, lol). Will open another later when we are ready to remove the Environment concept on the server side.
/close

**Pull request closed without merging**
