### PR TITLE
Add make command to docs to install dependencies

### PR DESCRIPTION
**Pull request by GotoRen**
**What this PR does / why we need it**:

Add the web config dependency install command to the documentation.
Developers run this command before building the Control Plane.

**Which issue(s) this PR fixes**:

Fixes https://github.com/pipe-cd/pipecd/issues/4546

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by kentakozuka** [comment]
Thanks for the PR!
Could you update your commit messages and add Sign-off-by information? We're following the DCO for now, and requires signing off every commits 🙏
https://pipecd.dev/docs/contribution-guidelines/contributing/#contributor-license-agreement

**Review by khanhtc1202 — APPROVED** [review]
Nice catch, thanks 🙌

**Comment by khanhtc1202** [comment]
@GotoRen Please sign-off your commit to make the CI passed 🙏 
https://pipecd.dev/docs/contribution-guidelines/contributing/#contributor-license-agreement

**Comment by GotoRen** [comment]
I signed-off !!

**Review by kentakozuka — APPROVED** [review]
Thanks 🚀

**Pull request merged**
