### PR TITLE
Refactor the logic of getting accounts in PLANNED event

### PR DESCRIPTION
**Pull request by ono-max**
**What this PR does / why we need it**:
This needs https://github.com/pipe-cd/pipe/pull/2640 to work well.
**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ono-max** [comment]
@nghialv 

Could you review this one? Thanks.

**Comment by ono-max** [comment]
@nghialv 

Updated 👍

**Comment by khanhtc1202** [comment]
> @khanhtc1202
> 
> Hmm, in my environment, there is no error when `make build`.

lets trigger rebuild 👌 
/trigger presubmit

**Comment by nghialv** [comment]
@ono-max You have to merge the latest master into your branch to have the same result at your local.
Because the previously merged PR already added that mentions variable.

https://github.com/pipe-cd/pipe/pull/2643/files

**Pull request merged**
