### PR TITLE
Add rfc for pipectl init

### PR DESCRIPTION
**Pull request by ouchi2501**
**What this PR does / why we need it**:

Add init to the pipectl command.
See below for Discussion.
https://github.com/pipe-cd/pipecd/discussions/4635

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Comment by kentakozuka** [comment]
Is it only app.pipecd.yaml that the first step(1. Create a configuration file from scratch) creates?

**Comment by ouchi2501** [comment]
https://github.com/pipe-cd/pipecd/pull/4672#issuecomment-1813670644
@kentakozuka 
Yes, Only app.pipecd.yaml

**Comment by kentakozuka** [comment]
As you mentions [here](https://github.com/pipe-cd/pipecd/discussions/4635#discussioncomment-7507636), would it be better to generate app.pipecd.yaml from applications's configs?
I input configs in [example](https://github.com/pipe-cd/pipecd/tree/master/examples/kubernetes/simple) and PipeCD's GPT output is the following. Looks not bad. WDYT?

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    # Specify the namespace if needed; otherwise, PipeCD deploys to the default namespace
    namespace: default
    kubernetes:
      manifests:
        - deployment.yaml
        - service.yaml
  pipeline:
    stages:
      # The primary deployment rollout
      - name: K8S_PRIMARY_ROLLOUT
      # The stage for manual approval (if needed)
      - name: WAIT_APPROVAL
      # The canary deployment rollout
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 50% # Adjust the percentage as required
      # The cleanup stage for the canary deployment
      - name: K8S_CANARY_CLEAN
  trafficRouting:
    method: pod
    kubernetes:
      primary:
        labels:
          pipecd.dev/variant: primary
      canary:
        labels:
          pipecd.dev/variant: canary

```

**Comment by ouchi2501** [comment]
I think it should have both features.
As for pipectl init, I think it would be less confusing for users if it was created as a general interactive init command rather than relying solely on GPT from the start!
However, I also think the ability to create a config from the application config through GPT would be very nice!
I think it would be nice to have the ability to create a config from the application config via GPT as an option for pipectl init!

**Comment by kentakozuka** [comment]
@ouchi2501 Sounds very cool! Let's stick with your plan :)

**Review by khanhtc1202 — APPROVED** [review]

**Pull request merged**
