### PR TITLE
Iterator implementation for filedb

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by knanao — COMMENTED** [review]
Looks good
/lgtm

**Comment by khanhtc1202** [comment]
I updated some tests, PTAL when you guys have time 🙆‍♀️

**Comment by nghialv** [comment]
Nice.
/approve

**Pull request merged**
