### PR TITLE
Update contributors list

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Welcome @Forget-C & @fazledyn-or :tada:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Review by ffjlabo — APPROVED** [review]
welcome🚀🚀

**Review by t-kikuc — APPROVED** [review]
nice!

**Comment by khanhtc1202** [comment]
お二人がまだ寝ないですか 🤣

**Comment by khanhtc1202** [comment]
対応早すぎるw

**Pull request merged**
