### PR TITLE
docs: added install method

### PR DESCRIPTION
**Pull request by ponkio-o**
**What this PR does / why we need it**:
I added install method using [aquaproj/aqua](https://github.com/aquaproj/aqua).
The aqua is a declarative CLI version manager, recently adopted by [various japanese tech companies](https://github.com/aquaproj/aqua?tab=readme-ov-file#who-uses-aqua). Our company also uses it. ([ref](https://github.com/orgs/aquaproj/discussions/2124#discussioncomment-8152619))

aqua-registry (It's like asdf-plugin) has been addressed in the following PR and is now available in [v4.163.0](https://github.com/aquaproj/aqua-registry/releases/tag/v4.163.0).
https://github.com/aquaproj/aqua-registry/pull/21955

**Which issue(s) this PR fixes**:
I added aqua to the pipectl command installation instructions.

**Does this PR introduce a user-facing change?**:
No.

### CODE REVIEW

**Comment by t-kikuc** [comment]
@ponkio-o 
Thank you so much for your great PRs, including aqua-registry's one!
It will help PipeCD reach more developers!

At first, please see https://github.com/pipe-cd/pipecd/pull/4875/checks?check_run_id=23936239937 and pass the DCO.  (roughly, you need  `git commit -s`)

**Review by t-kikuc — COMMENTED** [review]
The guide worked well and pipectl&piped are installed successfully by aqua!

For merging, would you copy the changes to the following two?:
- docs/content/en/docs-v0.47.x/quickstart/_index.md
- docs/content/en/docs-v0.47.x/user-guide/command-line-tool.md

That's because
- users can already install piped&pipectl by aqua (by your PR to aqua-registry)
- PipeCD's latest doc are redirected to the latest release version (v0.47.x now)
 e.g.  Go to https://pipecd.dev/docs/quickstart/ and you'll see https://pipecd.dev/docs-v0.47.x/quickstart/, not https://pipecd.dev/docs-dev/quickstart/.

**Comment by khanhtc1202** [comment]
@t-kikuc @ponkio-o 
We can use `make release/docs version=v0.47.0` to sync changes in `docs-dev/` to version v0.47.0 docs without manual copy 😉

**Comment by ponkio-o** [comment]
@t-kikuc @khanhtc1202 Thank you for review.
I synced to v0.47.x directory on the following commit.
https://github.com/pipe-cd/pipecd/pull/4875/commits/541870c0a0c28258d477f072248d9935bbaf4dad

**Review by khanhtc1202 — APPROVED** [review]
🚀🌝

**Pull request merged**
