### PR TITLE
Fix the docs to add analysis type

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Just don't remember which version we added the Datadog as AnalysisProvider 😂

**Review by khanhtc1202 — APPROVED** [review]
Nice catch

**Review by nghialv — APPROVED** [review]
Nice.

**Comment by knanao** [comment]
@khanhtc1202 
Me neither, but as you can know from the article, it would be after v0.25.0.
that's why this is fine🙌 
https://github.com/pipe-cd/pipecd/blob/master/docs/content/en/docs-v0.25.x/operator-manual/piped/adding-an-analysis-provider.md

**Pull request merged**
