### PR TITLE
Fix wrong BUILD.bazel file

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

This is being introduced in many pull requests. So I think it should be merged as soon as possible.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by khanhtc1202** [comment]
no objection 👌 cc @nakabonne 
/lgtm

**Comment by nakabonne** [comment]
Last week @knanao found out but I rejected as it's needed for https://github.com/pipe-cd/pipecd/pull/3124.
Is there anything that bothers you? In that case, let's merge it right now.

**Comment by nakabonne** [comment]
I am aware of what it's weird to have them now though.

**Comment by nghialv** [comment]
@nakabonne That change has been included in my last 3 PRs and every time I had to revert it. And I think #3124 will take time before it got merged so let's merge this to correct our master branch as soon as possible.

**Comment by nakabonne** [comment]
Alright! (Thank you @knanao too!)
/approve

**Pull request merged**
