### PR TITLE
Add project policies into role model

### PR DESCRIPTION
**Pull request by knanao**
**What this PR does / why we need it**:
`GetResouce` method is going to be used in two cases like below.

first case: check whether the user has enough resource permission to implement specific action in `service.pb.auth.go`.
```
// Authorize checks whether a role is enough for given gRPC method or not.
// Todo: Auto generate this file from protobuf.
func (a *authorizer) Authorize(method string, r model.Role) bool {
	switch method {
	case "/grpc.service.webservice.WebService/RegisterPiped":
		_, ok := r.GetResource(model.ProjectRBACResource_PIPED, model.ProjectRBACPolicy_CREATE)
		return isAdmin(r) || ok
   ...
	}

	return false
}
```

second case: check whether the user can handle the specific labels per API calls.
```
func (a *WebAPI) ListUnregisteredApplications(ctx context.Context, _ *webservice.ListUnregisteredApplicationsRequest) (*webservice.ListUnregisteredApplicationsResponse, error) {
	claims, err := rpcauth.ExtractClaims(ctx)
	if err != nil {
		a.logger.Error("failed to authenticate the current user", zap.Error(err))
		return nil, err
	}

	allApps, err := a.unregisteredAppStore.ListApplications(ctx, claims.Role.ProjectId)
	if errors.Is(err, cache.ErrNotFound) {
		return &webservice.ListUnregisteredApplicationsResponse{}, nil
	}
	if err != nil {
		a.logger.Error("failed to get unregistered apps", zap.Error(err))
		return nil, status.Error(codes.Internal, "Failed to get unregistered apps")
	}

	r, ok := claims.Role.GetResource(model.ProjectRBACResource_APPLICATION, model.ProjectRBACPolicy_LIST)
	if ok {
		ret := make([]*model.ApplicationInfo, 0, len(allApps))
		for _, v := range allApps {
			if r.Labels == nil || r.ContainLabels(v.Labels) {
				ret = append(ret, v)
			}
		}
		allApps = ret
	}

	if len(allApps) == 0 {
		return &webservice.ListUnregisteredApplicationsResponse{}, nil
	}

	sort.Slice(allApps, func(i, j int) bool {
		return allApps[i].Path < allApps[j].Path
	})

	return &webservice.ListUnregisteredApplicationsResponse{
		Applications: allApps,
	}, nil
}
```

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nghialv** [comment]
👀

**Review by knanao — COMMENTED** [review]
Let me hold this PR temporally.
/hold

**Comment by knanao** [comment]
@nghialv @khanhtc1202 
I have one point to confirm before fixing protoc plugin.
What do you think about the below implementation?
If it's okay, I'll fix protoc-gen-auth plugin to implement like below.

```
// Authorize checks whether a role is enough for given gRPC method or not.
// Todo: Auto generate this file from protobuf.
func (a *authorizer) Authorize(method string, r model.Role) bool {
	switch method {
	case "/grpc.service.webservice.WebService/RegisterPiped":
		_, ok := r.GetResource(model.ProjectRBACResource_PIPED, model.ProjectRBACPolicy_CREATE)
		return isAdmin(r) || ok
   ...
	}

	return false
}
```

**Comment by knanao** [comment]
Let me close this PR because I'll open the new PR.

**Pull request closed without merging**
