### PR TITLE
Add event context

### PR DESCRIPTION
**Pull request by ffjlabo**
**What this PR does**:

Add event context to the event.

**Why we need it**:

**Which issue(s) this PR fixes**:

Part of https://github.com/pipe-cd/pipecd/issues/5028

**Does this PR introduce a user-facing change?**:

- **How are users affected by this change**:
- **Is this breaking change**:
- **How to migrate (if breaking change)**:

### CODE REVIEW

**Review by t-kikuc — DISMISSED** [review]
good

**Review by Warashi — APPROVED** [review]
👍🏻

**Review by t-kikuc — APPROVED** [review]

**Review by khanhtc1202 — APPROVED** [review]
LGTM 👍

**Comment by ffjlabo** [comment]
📝 The sample for how the GitHub shows the trailers
```
commit 5fd3fdb367ac048fcae8533c5ea76d62e8e8998f (HEAD -> main, origin/main, origin/HEAD)
Author: Yoshiki Fujikane <ffjlabo@gmail.com>
Date:   Mon Oct 28 15:45:55 2024 +0900

    Update image version

    Source-Commit-Hash: 6512b1f3fcba7342c11cf96968e753c78e66561b
    Source-URL: https://github.com/pipe-cd/pipecd/commit/6512b1f3fcba7342c11cf96968e753c78e66561b
    PipeCD-Official-Docs: https://pipecd.dev/
```

Update_image_version_·_ca-dp_ffjlabo-dev_5fd3fdb (1)

**Pull request merged**
